### ISSUE TITLE
Create section view

### ISSUE THREAD

**Issue by sarn0ld** [collective/collective.frontpage#4]
1. The section view class should provide a HTML-snippet (div block) for the frontpage. (HTML to embed into frontpage view)
2. There should be a standalone section view (using the snippet)
3. Depending on Section Type there should be different page templates showing the following information:
  -  The background color and background image are defined in the schema-class already
  -  Title and description are defined in the schema-class already
  -  There should be a button visible if link_title is set in the schema-class.
  -  A click on the section title or the button should href to the link_url that is defined in the content-model
  -  If there is folderContent in the section (=Item Class): The grid of items should be shown with a card that includes Item- Title/Description/Icon/Image/Link/LinkTitle

**Comment by sarn0ld** [comment]
The snippets will be METAL-Macros

**Comment by sarn0ld** [comment]
Armin started this already. 
As fas as I can see 
- the item cards are missing.
- we don't have different pt files for the section types. (however not sure if this is necessary)

**Comment by Netroxen** [comment]
We currently have the following section types defined in the Python:

```python
items = [
  VocabItem(u"welcome", _(u"Welcome Section")),
  VocabItem(u"teaser", _(u"Teaser Section")),
  VocabItem(u"static", _(u"Static Section")),
  VocabItem(u"news", _(u"News Section")),
  VocabItem(u"tiles", _(u"Tiles Section")),
  VocabItem(u"search", _(u"Search Section")),
]
```

Can we please define what template styles should be displayed for each of the categories e.g.

* welcome -> full height / width container
* teaser -> full width container
* static -> text block section
* news -> 2 x 2 tiles
* tiles -> 4 x 4 tiles
* search -> search section container

Can you please verify what styling is wanted, cheers!

**Comment by sarn0ld** [comment]
You are right, this needs some better requirements specification. 
I will create separate issues for the section types.

This issue can be closed, then.
